---
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.4.1
    hooks:
      - id: commitizen
        stages: 
          - commit-msg
        additional_dependencies: [cz-github-jira-conventional]
