---
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.4.1
    hooks:
      - id: commitizen
        stages: 
          - commit-msg
        additional_dependencies: [cz-github-jira-conventional]
  - repo: local
    hooks:
    # NGUI-108 disabled. formatting is still part of CI pipeline but is responsibility of developer to run it
    #   - id: pants-fmt
    #     name: pants fmt
    #     always_run: false
    #     description: runs pants fmt on python files
    #     entry: pants --no-dynamic-ui fmt
    #     language: system
    #     pass_filenames: true
    #     types: [file,python]
      - id: pants-lint
        name: pants lint
        always_run: false
        description: runs pants lint on python files
        entry: pants lint
        language: system
        pass_filenames: true
        types: [file,python]
      - id: pants-check
        name: pants check
        always_run: false
        description: runs pants check on python files
        entry: pants check
        language: system
        pass_filenames: true
        types: [file,python]
