# See https://www.pantsbuild.org/docs/using-pants-in-ci.

[GLOBAL]
dynamic_ui = false
colors = true

# Set to `true` if you have a Pants remote cache provider available for CI builds
remote_cache_read = false
remote_cache_write = false

[python]
interpreter_constraints = ["CPython>=3.11,<3.14"]

[pytest]
args = ["-vv", "--no-header"]

[tailor]
ignore_paths = [
    'tests/distribution-all/**',
]

[coverage-py]
report = ["raw"]

[test]
report = true
use_coverage = true
