[GLOBAL]
pants_version = "2.24.2"
backend_packages.add = [
  "pants.backend.build_files.fmt.black",  
  "pants.backend.python",
#  "pants.backend.python.lint.docformatter", - commented out due to error
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
]
pants_ignore = [
  "requirements_dev.txt"
]

[source]
# The Python source root is the repo root. See https://www.pantsbuild.org/docs/source-roots.
root_patterns = ["/libs", "/tests", "/spec"]

[python]
# Project supported versions.
interpreter_constraints = ["CPython>=3.11,<3.14"]

# Enable the "resolves" mechanism, which turns on lockfiles for user code. See
# https://www.pantsbuild.org/docs/python-third-party-dependencies. This also adds the
# `generate-lockfiles` goal for Pants to generate the lockfile for you.
enable_resolves = true

[python.resolves]
python-default = "python-default.lock"
flake8 = "libs/3rdparty/python/flake8.lock"

[python.resolves_to_constraints_file]
python-default = "libs/3rdparty/python/llama-stack-client-constraints.txt"

[export]
py_resolve_format = "symlinked_immutable_virtualenv"
resolve = [
    'flake8',
    'python-default',
]

[python-bootstrap]
# We search for interpreters both on the $PATH and in the `$(pyenv root)/versions` folder.
#  If you're using macOS, you may want to leave off the <PATH> entry to avoid using the
#  problematic system Pythons. See
#  https://www.pantsbuild.org/docs/python-interpreter-compatibility#changing-the-interpreter-search-path.
search_path = ["<PATH>", "<PYENV>"]

[tailor]
ignore_paths = [
    'tests/distribution-all/**',
]

[pytest]
args = ["--no-header", "-vv"]
execution_slot_var = "TEST_EXECUTION_SLOT"
requirements = ["//libs/3rdparty/python:pytest"]

[flake8]
install_from_resolve = "flake8"
requirements = ["//libs/3rdparty/python:flake8"]

