# See https://www.pantsbuild.org/docs/using-pants-in-ci.

[GLOBAL]
dynamic_ui = false
colors = true

# Set to `true` if you have a Pants remote cache provider available for CI builds
remote_cache_read = false
remote_cache_write = false

[pytest]
args = ["--no-header", "-vv", "--strict-markers"]
execution_slot_var = "TEST_EXECUTION_SLOT"
requirements = ["//libs/3rdparty/python:pytest"]

[tailor]
ignore_paths = [
    'tests/distribution-all/**',
]

[coverage-py]
report = ["raw"]

[test]
report = true
use_coverage = true
