# This target sets the metadata for all the Python non-test files in this directory.
python_sources(
    name="assistant_api",
    dependencies=[
        "libs/next_gen_ui_langgraph:lib",
        "libs/3rdparty/python:langchain",
        "libs/3rdparty/python:ngui-e2e-server",
    ],
)
