# Next Gen UI MCP Server

# Build locally
# pants package ::
#
# In case you're using podman instead of docker, you have to alias docker command to podman in order for Pants to use it.
#
# sudo ln -s $(which podman) /usr/local/bin/docker
#
# Make sure the /usr/local/bin path is in the $PATH environment variable.
#
# Also it may happen that the command will fail with an error that the image named 4 lines below doesn't exist.
# This can be fixed by first pulling the image with podman:
#
# podman pull registry.access.redhat.com/ubi9/python-312-minimal:9.6
#
#
# Run:
# podman run --rm -it -p 5000:5000 --env MCP_PORT="5000" --env NGUI_MODEL="llama3.2" --env NGUI_PROVIDER_API_BASE_URL=http://host.containers.internal:11434 --env NGUI_PROVIDER_API_KEY="ollama" quay.io/next-gen-ui/mcp
FROM registry.access.redhat.com/ubi9/python-312-minimal:9.6

# Set work directory
WORKDIR /opt/app-root/src

# Set environment variables for build
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PIP_NO_CACHE_DIR=1

# Copy Python Project Files (Container context must be the `python` directory)
COPY --chown=1001:root . /opt/app-root/src/

USER root

# Install dependencies
RUN pip install *.whl \
    langchain_openai

# Allow non-root user to access the everything in app-root
RUN chgrp -R root /opt/app-root/src && chmod -R g+rwx /opt/app-root/src

# env variables supported by the MCP server
ENV MCP_TRANSPORT="streamable-http"
ENV MCP_HOST="0.0.0.0"
ENV MCP_PORT="5000"
ENV MCP_TOOLS=""
ENV MCP_STRUCTURED_OUTPUT_ENABLED="true"
ENV NGUI_CONFIG_PATH=""
ENV NGUI_COMPONENT_SYSTEM=""
ENV NGUI_PROVIDER="openai"
ENV NGUI_PROVIDER_API_KEY=""
ENV NGUI_PROVIDER_API_BASE_URL=""
ENV NGUI_MODEL="gpt-4o"
ENV NGUI_PROVIDER_TEMPERATURE=""
ENV NGUI_SAMPLING_MAX_TOKENS=""
ENV NGUI_PROVIDER_ANTHROPIC_VERSION=""
ENV NGUI_SAMPLING_HINTS=""
ENV NGUI_SAMPLING_COST_PRIORITY=""
ENV NGUI_SAMPLING_SPEED_PRIORITY=""
ENV NGUI_SAMPLING_INTELLIGENCE_PRIORITY=""

# Expose default port (change if needed)
EXPOSE $MCP_PORT

USER 1001

# Run the MCP
CMD python -m next_gen_ui_mcp
